//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("SCA_DepCulturaModel", "FK_User_Permission", "Permission", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Permission), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Users), true)]

#endregion

namespace DataAccessLayer
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SCA_DepCulturaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SCA_DepCulturaEntities usando la cadena de conexión encontrada en la sección 'SCA_DepCulturaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public SCA_DepCulturaEntities() : base("name=SCA_DepCulturaEntities", "SCA_DepCulturaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SCA_DepCulturaEntities.
        /// </summary>
        public SCA_DepCulturaEntities(string connectionString) : base(connectionString, "SCA_DepCulturaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SCA_DepCulturaEntities.
        /// </summary>
        public SCA_DepCulturaEntities(EntityConnection connection) : base(connection, "SCA_DepCulturaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Permission> Permission
        {
            get
            {
                if ((_Permission == null))
                {
                    _Permission = base.CreateObjectSet<Permission>("Permission");
                }
                return _Permission;
            }
        }
        private ObjectSet<Permission> _Permission;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Permission. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPermission(Permission permission)
        {
            base.AddObject("Permission", permission);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Users. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SCA_DepCulturaModel", Name="Permission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Permission : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Permission.
        /// </summary>
        /// <param name="idPermission">Valor inicial de la propiedad idPermission.</param>
        /// <param name="name">Valor inicial de la propiedad Name.</param>
        /// <param name="description">Valor inicial de la propiedad Description.</param>
        public static Permission CreatePermission(global::System.Int32 idPermission, global::System.String name, global::System.String description)
        {
            Permission permission = new Permission();
            permission.idPermission = idPermission;
            permission.Name = name;
            permission.Description = description;
            return permission;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPermission
        {
            get
            {
                return _idPermission;
            }
            set
            {
                if (_idPermission != value)
                {
                    OnidPermissionChanging(value);
                    ReportPropertyChanging("idPermission");
                    _idPermission = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPermission");
                    OnidPermissionChanged();
                }
            }
        }
        private global::System.Int32 _idPermission;
        partial void OnidPermissionChanging(global::System.Int32 value);
        partial void OnidPermissionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SCA_DepCulturaModel", "FK_User_Permission", "Users")]
        public EntityCollection<Users> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Users>("SCA_DepCulturaModel.FK_User_Permission", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Users>("SCA_DepCulturaModel.FK_User_Permission", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SCA_DepCulturaModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Users.
        /// </summary>
        /// <param name="idUser">Valor inicial de la propiedad idUser.</param>
        /// <param name="userName">Valor inicial de la propiedad userName.</param>
        /// <param name="password">Valor inicial de la propiedad password.</param>
        /// <param name="permission">Valor inicial de la propiedad permission.</param>
        /// <param name="higthDate">Valor inicial de la propiedad HigthDate.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="secondName">Valor inicial de la propiedad secondName.</param>
        public static Users CreateUsers(global::System.Int32 idUser, global::System.String userName, global::System.String password, global::System.Int32 permission, global::System.DateTime higthDate, global::System.String name, global::System.String secondName)
        {
            Users users = new Users();
            users.idUser = idUser;
            users.userName = userName;
            users.password = password;
            users.permission = permission;
            users.HigthDate = higthDate;
            users.name = name;
            users.secondName = secondName;
            return users;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idUser
        {
            get
            {
                return _idUser;
            }
            set
            {
                if (_idUser != value)
                {
                    OnidUserChanging(value);
                    ReportPropertyChanging("idUser");
                    _idUser = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idUser");
                    OnidUserChanged();
                }
            }
        }
        private global::System.Int32 _idUser;
        partial void OnidUserChanging(global::System.Int32 value);
        partial void OnidUserChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 permission
        {
            get
            {
                return _permission;
            }
            set
            {
                OnpermissionChanging(value);
                ReportPropertyChanging("permission");
                _permission = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("permission");
                OnpermissionChanged();
            }
        }
        private global::System.Int32 _permission;
        partial void OnpermissionChanging(global::System.Int32 value);
        partial void OnpermissionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime HigthDate
        {
            get
            {
                return _HigthDate;
            }
            set
            {
                OnHigthDateChanging(value);
                ReportPropertyChanging("HigthDate");
                _HigthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HigthDate");
                OnHigthDateChanged();
            }
        }
        private global::System.DateTime _HigthDate;
        partial void OnHigthDateChanging(global::System.DateTime value);
        partial void OnHigthDateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String secondName
        {
            get
            {
                return _secondName;
            }
            set
            {
                OnsecondNameChanging(value);
                ReportPropertyChanging("secondName");
                _secondName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("secondName");
                OnsecondNameChanged();
            }
        }
        private global::System.String _secondName;
        partial void OnsecondNameChanging(global::System.String value);
        partial void OnsecondNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String secondSurname
        {
            get
            {
                return _secondSurname;
            }
            set
            {
                OnsecondSurnameChanging(value);
                ReportPropertyChanging("secondSurname");
                _secondSurname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("secondSurname");
                OnsecondSurnameChanged();
            }
        }
        private global::System.String _secondSurname;
        partial void OnsecondSurnameChanging(global::System.String value);
        partial void OnsecondSurnameChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SCA_DepCulturaModel", "FK_User_Permission", "Permission")]
        public Permission Permission1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Permission>("SCA_DepCulturaModel.FK_User_Permission", "Permission").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Permission>("SCA_DepCulturaModel.FK_User_Permission", "Permission").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Permission> Permission1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Permission>("SCA_DepCulturaModel.FK_User_Permission", "Permission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Permission>("SCA_DepCulturaModel.FK_User_Permission", "Permission", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
